### ISSUE TITLE
NPE while using the plugin.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/BetterDocs#135]
null
java.lang.NullPointerException
	at com.imaginea.betterdocs.EditorDocOps.getImports(EditorDocOps.java:148)
	at com.imaginea.betterdocs.RefreshAction.getImports(RefreshAction.java:236)
	at com.imaginea.betterdocs.RefreshAction.runWorker(RefreshAction.java:197)
	at com.imaginea.betterdocs.RefreshAction.access$200(RefreshAction.java:69)
	at com.imaginea.betterdocs.RefreshAction$ProjectNodesWorker.run(RefreshAction.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.imaginea.betterdocs.RefreshAction$1.call(RefreshAction.java:157)
	at com.imaginea.betterdocs.RefreshAction$1.call(RefreshAction.java:152)
	at com.intellij.openapi.application.impl.ApplicationImpl$9.call(ApplicationImpl.java:430)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by prudhvije** [comment]
Building Psi files for non java files is failing with NPE. Have to implement alternative way of getting imports.

**Comment by ScrapCodes** [comment]
There is no need for supporting non java files, show proper dialogue and fail gracefully.

**Comment by ScrapCodes** [comment]
With dialogue, I meant showHelpInfo.
